spring:
  application:
    name: developer-shop
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  # driver config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://dokalab.asuscomm.com:50133/devshop
    username: devshop
    password: 1234

server:
  port: 8080

# mybatis config
mybatis:
  mapper-locations: mappers/**/*.xml

logging:
  level:
    com.nf404.devshop: DEBUG
    com.nf404.devshop.mapper: DEBUG